Added code for Kosaraju Algorithm
ZoranPandovski/al-go-rithms pull request #2537
Opened 2020-10-13 18:05 UTC by errpv78

**Added Kosaraju algorithm for strongly connected components in graph** 

**Changes:**
Followed the format as given with the algorithm name as the folder. It contains a python code file and a readme file explaining the algorithm.

2020-10-16 16:09 UTC, ZoranPandovski requested changes
Please add it to data_structures/graph

2020-10-17 04:23 UTC, errpv78 reviewed
Kosaraju moved to data_structures/Graphs

2020-10-17 04:23 UTC, errpv78 commented
Changes committed

2020-10-17 17:58 UTC, ZoranPandovski approved these changes

2020-10-17 17:58 UTC, merged