palindrome check in c++ aded
ZoranPandovski/al-go-rithms pull request #2573
Opened 2020-10-18 02:24 UTC by nausherofficial

**Fixes issue:** #2561 

**Changes:**
*/Added algorithm for checking palindrome number in c++*/

2020-10-18 16:25 UTC, ZoranPandovski requested changes
Please add it to math dir

2020-10-18 16:31 UTC, nausherofficial commented
> Please add it to math dir

Ok I will do it.

2020-10-18 17:05 UTC, nausherofficial commented
> > Please add it to math dir
> 
> Ok I will do it.

I have done the changes suggested by you please review and merge it or add hacktoberfest-accepted label

2020-10-25 14:18 UTC, ZoranPandovski approved these changes

2020-10-25 14:18 UTC, merged