added next greatest element and next smaller element using stack
ZoranPandovski/al-go-rithms pull request #3213
Opened 2022-10-02 09:56 UTC by Anunaya07

This is a(n):

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

Details:

#### Next Greatest Elements(NGE): 
NGE Problem states that for a given list of positive integer we need to find the greatest integer closest to it otherwise -1.
example: given: [1,5,3,4] 1 will be replaced by 5, 5 will replaced by -1, and so on. (answer: [5,-1,4,-1])

#### Next Smaller Elements(NSE): 
NSE Problem states that for a given list of positive integer we need to find the smaller integer closest to it otherwise -1.
example: given: [1,5,3,4] 1 will be replaced by -1, 5 will replaced by 3, and so on.(answer: [-1,3,-1,-1])

The pseudo-code is as follows : -

```
for i in range(len(given list)-1,-1,-1): 

    if check if stack is empty:
        if true append -1 in stack
    else:
        if check if top is greater:  
            if true append top in stack
        else:
            while (pop until we reach an element greater than given element 
                or till the stack is exhausted)

            if check stack is empty:
                if true append -1
            else:
                if stack not empty append top
    
    append the element from the list into stack
```

Time Complexity: - O(n)
Space Complexity: - O(n)

**Changes:**
Added two python files in stack folder.

2022-10-03 11:22 UTC, ZoranPandovski requested changes
Can you please move this to data structures dir?

2022-10-04 17:20 UTC, Anunaya07 commented
@ZoranPandovski Okay I will do it immediately : ). Thank you for reviewing my PR.

2022-10-04 17:30 UTC, Anunaya07 commented
@ZoranPandovski I have moved the files in ds dir in stack folder. Please accept my PR under hacktoberfest.

2022-10-05 08:03 UTC, ZoranPandovski approved these changes

2022-10-05 08:04 UTC, merged