Corrected file name of a cpp file in sort/ folder
ZoranPandovski/al-go-rithms pull request #3345
Opened 2022-10-14 06:08 UTC by RoyCoding8

**Fixes issue:** #[3333]

**Changes:**
An invalid file name was not allowing a successful clone for contributions. Changed the file name to remove special characters and allow cloning

2022-10-14 13:52 UTC, ZoranPandovski requested changes
CAn you please simplify the name>

2022-10-14 14:39 UTC, RoyCoding8 commented
@ZoranPandovski "Sort_an_array_of_0s,_1s_and_2s|Dutch_National_Flag_problem.cpp"

2022-10-15 04:30 UTC, RoyCoding8 commented
@ZoranPandovski Done! Please review :)

2022-10-17 09:27 UTC, ZoranPandovski approved these changes

2022-10-17 09:27 UTC, merged